# Generated by Django 3.2.4 on 2022-04-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle_records',
            old_name='concentrate',
            new_name='concentrate1',
        ),
        migrations.RenameField(
            model_name='cattle_records',
            old_name='quality',
            new_name='quality1',
        ),
        migrations.AddField(
            model_name='cattle_records',
            name='concentrate2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cattle_records',
            name='quality2',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
