# Generated by Django 3.2.4 on 2022-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd_management', '0002_auto_20220411_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle_records',
            name='no_of_location',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccination_record',
            name='date_vaccination',
            field=models.IntegerField(null=True),
        ),
    ]
