# Generated by Django 3.2.4 on 2022-04-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herd_management', '0004_auto_20220411_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle_records',
            old_name='no_of_location',
            new_name='no_of_loctaion',
        ),
    ]
