# Generated by Django 3.2.4 on 2022-04-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herd_management', '0005_rename_no_of_location_cattle_records_no_of_loctaion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cattle_records',
            old_name='no_of_loctaion',
            new_name='no_of_lactation',
        ),
    ]
